spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  # spring security removed or commented out
  # security:
  #   user:
  #     name: admin
  #     password: admin123
